name: Publish Docker image
on:
  push: 
    branches: master

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Moving build to artifacts directory
        env: 
          TRIGO_PACKAGE_ACCESS_TOKEN: ${{ secrets.TRIGO_PACKAGE_ACCESS_TOKEN }}
        run: chmod +x ./action-a/ghcr-upload.sh
        run: ./action-a/ghcr-upload.sh